// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package people_in_charge

import (
	"git.d.foundation/datcom/backend/models"
	"git.d.foundation/datcom/backend/src/domain"
	"sync"
)

var (
	lockServiceMockAdd   sync.RWMutex
	lockServiceMockExist sync.RWMutex
	lockServiceMockGet   sync.RWMutex
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//     func TestSomethingThatUsesService(t *testing.T) {
//
//         // make and configure a mocked Service
//         mockedService := &ServiceMock{
//             AddFunc: func(p *domain.PeopleInCharge) (*models.PeopleInCharge, error) {
// 	               panic("mock out the Add method")
//             },
//             ExistFunc: func(p *domain.PeopleInCharge) (bool, error) {
// 	               panic("mock out the Exist method")
//             },
//             GetFunc: func(menuID int) ([]*domain.PeopleInCharge, error) {
// 	               panic("mock out the Get method")
//             },
//         }
//
//         // use mockedService in code that requires Service
//         // and then make assertions.
//
//     }
type ServiceMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(p *domain.PeopleInCharge) (*models.PeopleInCharge, error)

	// ExistFunc mocks the Exist method.
	ExistFunc func(p *domain.PeopleInCharge) (bool, error)

	// GetFunc mocks the Get method.
	GetFunc func(menuID int) ([]*domain.PeopleInCharge, error)

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// P is the p argument value.
			P *domain.PeopleInCharge
		}
		// Exist holds details about calls to the Exist method.
		Exist []struct {
			// P is the p argument value.
			P *domain.PeopleInCharge
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// MenuID is the menuID argument value.
			MenuID int
		}
	}
}

// Add calls AddFunc.
func (mock *ServiceMock) Add(p *domain.PeopleInCharge) (*models.PeopleInCharge, error) {
	if mock.AddFunc == nil {
		panic("ServiceMock.AddFunc: method is nil but Service.Add was just called")
	}
	callInfo := struct {
		P *domain.PeopleInCharge
	}{
		P: p,
	}
	lockServiceMockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	lockServiceMockAdd.Unlock()
	return mock.AddFunc(p)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//     len(mockedService.AddCalls())
func (mock *ServiceMock) AddCalls() []struct {
	P *domain.PeopleInCharge
} {
	var calls []struct {
		P *domain.PeopleInCharge
	}
	lockServiceMockAdd.RLock()
	calls = mock.calls.Add
	lockServiceMockAdd.RUnlock()
	return calls
}

// Exist calls ExistFunc.
func (mock *ServiceMock) Exist(p *domain.PeopleInCharge) (bool, error) {
	if mock.ExistFunc == nil {
		panic("ServiceMock.ExistFunc: method is nil but Service.Exist was just called")
	}
	callInfo := struct {
		P *domain.PeopleInCharge
	}{
		P: p,
	}
	lockServiceMockExist.Lock()
	mock.calls.Exist = append(mock.calls.Exist, callInfo)
	lockServiceMockExist.Unlock()
	return mock.ExistFunc(p)
}

// ExistCalls gets all the calls that were made to Exist.
// Check the length with:
//     len(mockedService.ExistCalls())
func (mock *ServiceMock) ExistCalls() []struct {
	P *domain.PeopleInCharge
} {
	var calls []struct {
		P *domain.PeopleInCharge
	}
	lockServiceMockExist.RLock()
	calls = mock.calls.Exist
	lockServiceMockExist.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ServiceMock) Get(menuID int) ([]*domain.PeopleInCharge, error) {
	if mock.GetFunc == nil {
		panic("ServiceMock.GetFunc: method is nil but Service.Get was just called")
	}
	callInfo := struct {
		MenuID int
	}{
		MenuID: menuID,
	}
	lockServiceMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockServiceMockGet.Unlock()
	return mock.GetFunc(menuID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedService.GetCalls())
func (mock *ServiceMock) GetCalls() []struct {
	MenuID int
} {
	var calls []struct {
		MenuID int
	}
	lockServiceMockGet.RLock()
	calls = mock.calls.Get
	lockServiceMockGet.RUnlock()
	return calls
}
