// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package menu

import (
	"sync"

	"git.d.foundation/datcom/backend/models"
	"git.d.foundation/datcom/backend/src/domain"
)

var (
	lockServiceMockFindByID sync.RWMutex
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//     func TestSomethingThatUsesService(t *testing.T) {
//
//         // make and configure a mocked Service
//         mockedService := &ServiceMock{
//             FindByIDFunc: func(mn *domain.MenuInput) (*models.Menu, error) {
// 	               panic("mock out the FindByID method")
//             },
//         }
//
//         // use mockedService in code that requires Service
//         // and then make assertions.
//
//     }
type ServiceMock struct {
	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(mn *domain.MenuInput) (*models.Menu, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Mn is the mn argument value.
			Mn *domain.MenuInput
		}
	}
}

// FindByID calls FindByIDFunc.
func (mock *ServiceMock) FindByID(mn *domain.MenuInput) (*models.Menu, error) {
	if mock.FindByIDFunc == nil {
		panic("ServiceMock.FindByIDFunc: method is nil but Service.FindByID was just called")
	}
	callInfo := struct {
		Mn *domain.MenuInput
	}{
		Mn: mn,
	}
	lockServiceMockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	lockServiceMockFindByID.Unlock()
	return mock.FindByIDFunc(mn)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//     len(mockedService.FindByIDCalls())
func (mock *ServiceMock) FindByIDCalls() []struct {
	Mn *domain.MenuInput
} {
	var calls []struct {
		Mn *domain.MenuInput
	}
	lockServiceMockFindByID.RLock()
	calls = mock.calls.FindByID
	lockServiceMockFindByID.RUnlock()
	return calls
}
