// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package menu

import (
	"git.d.foundation/datcom/backend/models"
	"sync"
)

var (
	lockServiceMockCheckMenuExist sync.RWMutex
	lockServiceMockFindMenu       sync.RWMutex
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//     func TestSomethingThatUsesService(t *testing.T) {
//
//         // make and configure a mocked Service
//         mockedService := &ServiceMock{
//             CheckMenuExistFunc: func(menuID int) (bool, error) {
// 	               panic("mock out the CheckMenuExist method")
//             },
//             FindMenuFunc: func(m *Menu) (*models.Menu, error) {
// 	               panic("mock out the FindMenu method")
//             },
//         }
//
//         // use mockedService in code that requires Service
//         // and then make assertions.
//
//     }
type ServiceMock struct {
	// CheckMenuExistFunc mocks the CheckMenuExist method.
	CheckMenuExistFunc func(menuID int) (bool, error)

	// FindMenuFunc mocks the FindMenu method.
	FindMenuFunc func(m *Menu) (*models.Menu, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckMenuExist holds details about calls to the CheckMenuExist method.
		CheckMenuExist []struct {
			// MenuID is the menuID argument value.
			MenuID int
		}
		// FindMenu holds details about calls to the FindMenu method.
		FindMenu []struct {
			// M is the m argument value.
			M *Menu
		}
	}
}

// CheckMenuExist calls CheckMenuExistFunc.
func (mock *ServiceMock) CheckMenuExist(menuID int) (bool, error) {
	if mock.CheckMenuExistFunc == nil {
		panic("ServiceMock.CheckMenuExistFunc: method is nil but Service.CheckMenuExist was just called")
	}
	callInfo := struct {
		MenuID int
	}{
		MenuID: menuID,
	}
	lockServiceMockCheckMenuExist.Lock()
	mock.calls.CheckMenuExist = append(mock.calls.CheckMenuExist, callInfo)
	lockServiceMockCheckMenuExist.Unlock()
	return mock.CheckMenuExistFunc(menuID)
}

// CheckMenuExistCalls gets all the calls that were made to CheckMenuExist.
// Check the length with:
//     len(mockedService.CheckMenuExistCalls())
func (mock *ServiceMock) CheckMenuExistCalls() []struct {
	MenuID int
} {
	var calls []struct {
		MenuID int
	}
	lockServiceMockCheckMenuExist.RLock()
	calls = mock.calls.CheckMenuExist
	lockServiceMockCheckMenuExist.RUnlock()
	return calls
}

// FindMenu calls FindMenuFunc.
func (mock *ServiceMock) FindMenu(m *Menu) (*models.Menu, error) {
	if mock.FindMenuFunc == nil {
		panic("ServiceMock.FindMenuFunc: method is nil but Service.FindMenu was just called")
	}
	callInfo := struct {
		M *Menu
	}{
		M: m,
	}
	lockServiceMockFindMenu.Lock()
	mock.calls.FindMenu = append(mock.calls.FindMenu, callInfo)
	lockServiceMockFindMenu.Unlock()
	return mock.FindMenuFunc(m)
}

// FindMenuCalls gets all the calls that were made to FindMenu.
// Check the length with:
//     len(mockedService.FindMenuCalls())
func (mock *ServiceMock) FindMenuCalls() []struct {
	M *Menu
} {
	var calls []struct {
		M *Menu
	}
	lockServiceMockFindMenu.RLock()
	calls = mock.calls.FindMenu
	lockServiceMockFindMenu.RUnlock()
	return calls
}
