// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package menu

import (
	"git.d.foundation/datcom/backend/models"
	"sync"
)

var (
	lockServiceMockFindMenu sync.RWMutex
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//     func TestSomethingThatUsesService(t *testing.T) {
//
//         // make and configure a mocked Service
//         mockedService := &ServiceMock{
//             FindMenuFunc: func(m *Menu) (*models.Menu, error) {
// 	               panic("mock out the FindMenu method")
//             },
//         }
//
//         // use mockedService in code that requires Service
//         // and then make assertions.
//
//     }
type ServiceMock struct {
	// FindMenuFunc mocks the FindMenu method.
	FindMenuFunc func(m *Menu) (*models.Menu, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindMenu holds details about calls to the FindMenu method.
		FindMenu []struct {
			// M is the m argument value.
			M *Menu
		}
	}
}

// FindMenu calls FindMenuFunc.
func (mock *ServiceMock) FindMenu(m *Menu) (*models.Menu, error) {
	if mock.FindMenuFunc == nil {
		panic("ServiceMock.FindMenuFunc: method is nil but Service.FindMenu was just called")
	}
	callInfo := struct {
		M *Menu
	}{
		M: m,
	}
	lockServiceMockFindMenu.Lock()
	mock.calls.FindMenu = append(mock.calls.FindMenu, callInfo)
	lockServiceMockFindMenu.Unlock()
	return mock.FindMenuFunc(m)
}

// FindMenuCalls gets all the calls that were made to FindMenu.
// Check the length with:
//     len(mockedService.FindMenuCalls())
func (mock *ServiceMock) FindMenuCalls() []struct {
	M *Menu
} {
	var calls []struct {
		M *Menu
	}
	lockServiceMockFindMenu.RLock()
	calls = mock.calls.FindMenu
	lockServiceMockFindMenu.RUnlock()
	return calls
}
