// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Items          string
	Menus          string
	Orders         string
	PeopleInCharge string
	Users          string
}{
	Items:          "items",
	Menus:          "menus",
	Orders:         "orders",
	PeopleInCharge: "people_in_charge",
	Users:          "users",
}
